development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cat_world_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cat_world_test
  pool: 5
